data=[
    {
        "item":"espresso",
        "water":50,
        "milk":0,
        "coffee":18,
        "price":1.50
    },
    {
        "item":"latte",
        "water":200,
        "milk":150,
        "coffee":24,
        "price":2.50
    },
    {
        "item":"cappuccino",
        "water":250,
        "milk":100,
        "coffee":24,
        "price":3.00
    }
]